name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.4-slim
      env:
        MIX_ENV: test
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
        env:
          RABBITMQ_USER: guest
          RABBITMQ_PASS: guest
          RABBITMQ_VHOST: "/"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - uses: actions/cache@v1
        with:
          path: _build/test
          key: ${{ runner.os }}-test-build
          restore-keys: |
            ${{ runner.os }}-test-build
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix test
        env:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: ${{ job.services.rabbitmq.ports[5672] }}
          RABBITMQ_USER: guest
          RABBITMQ_PASSWORD: guest
